export const testData1 = [
  { type: "衣物衣物衣物衣物衣物销量", clothing: "衬衫", sales: 5 },
  { type: "衣物衣物衣物衣物衣物销量", clothing: "羊毛衫", sales: 20 },
  { type: "衣物衣物衣物衣物衣物销量", clothing: "雪纺衫", sales: 36 },
  { type: "衣物衣物衣物衣物衣物销量", clothing: "裤子", sales: 10 },
  { type: "衣物衣物衣物衣物衣物销量", clothing: "高跟鞋", sales: 10 },
  { type: "衣物衣物衣物衣物衣物销量", clothing: "袜子", sales: 56 },
  { type: "衣物衣物衣物衣物衣物库存", clothing: "衬衫", sales: 2 },
  { type: "衣物衣物衣物衣物衣物库存", clothing: "羊毛衫", sales: 9 },
  { type: "衣物衣物衣物衣物衣物库存", clothing: "雪纺衫", sales: 17 },
  { type: "衣物衣物衣物衣物衣物库存", clothing: "裤子", sales: 3 },
  { type: "衣物衣物衣物衣物衣物库存", clothing: "高跟鞋", sales: 28 },
  { type: "衣物衣物衣物衣物衣物库存", clothing: "袜子", sales: 12 },
  { type: "衣物衣物衣物衣物衣物破损", clothing: "衬衫", sales: 5 },
  { type: "衣物衣物衣物衣物衣物破损", clothing: "羊毛衫", sales: 23 },
  { type: "衣物衣物衣物衣物衣物破损", clothing: "雪纺衫", sales: 8 },
  { type: "衣物衣物衣物衣物衣物破损", clothing: "裤子", sales: 11 },
  { type: "衣物衣物衣物衣物衣物破损", clothing: "高跟鞋", sales: 7 },
  { type: "衣物衣物衣物衣物衣物破损", clothing: "袜子", sales: 32 },
  // { type: "衣物衣物衣物衣物衣物回退", clothing: "衬衫", sales: 39 },
  // { type: "衣物衣物衣物衣物衣物回退", clothing: "羊毛衫", sales: 12 },
  // { type: "衣物衣物衣物衣物衣物回退", clothing: "雪纺衫", sales: 4 },
  // { type: "衣物衣物衣物衣物衣物回退", clothing: "裤子", sales: 27 },
  // { type: "衣物衣物衣物衣物衣物回退", clothing: "高跟鞋", sales: 19 },
  // { type: "衣物衣物衣物衣物衣物回退", clothing: "袜子", sales: 42 },
  // { type: "衣物销量", clothing: "袜子1", sales: 22 },
  // { type: "衣物销量", clothing: "袜子2", sales: 22 },
  // { type: "衣物销量", clothing: "袜子3", sales: 22 },
  // { type: "衣物销量", clothing: "袜子4", sales: 22 },
  // { type: "衣物销量", clothing: "袜子5", sales: 22 },
  // { type: "衣物销量", clothing: "袜子6", sales: 22 },
  // { type: "衣物销量", clothing: "袜子7", sales: 22 },
  // { type: "衣物销量", clothing: "袜子8", sales: 22 },
  // { type: "衣物销量", clothing: "袜子9", sales: 22 },
  // { type: "衣物销量", clothing: "袜子10", sales: 22 },
  // { type: "衣物销量", clothing: "袜子11", sales: 22 },
  // { type: "衣物销量", clothing: "袜子12", sales: 22 },
  // { type: "衣物销量", clothing: "袜子13", sales: 22 },
  // { type: "衣物销量", clothing: "袜子14", sales: 22 },
  // { type: "衣物销量", clothing: "袜子15", sales: 22 },
  // { type: "衣物销量", clothing: "袜子16", sales: 22 },
  // { type: "衣物销量", clothing: "袜子17", sales: 22 },
  // { type: "衣物销量", clothing: "袜子18", sales: 22 },
  // { type: "衣物销量", clothing: "袜子19", sales: 28 },
  // { type: "衣物销量", clothing: "袜子20", sales: 22 },
  // { type: "衣物销量", clothing: "袜子21", sales: 22 },
  // { type: "衣物销量", clothing: "袜子22", sales: 22 },
  // { type: "衣物销量", clothing: "袜子23", sales: 22 },
  // { type: "衣物销量", clothing: "袜子24", sales: 22 },
  // { type: "衣物销量", clothing: "袜子25", sales: 22 },
  // { type: "衣物销量", clothing: "袜子26", sales: 22 },
  // { type: "衣物销量", clothing: "袜子27", sales: 22 },
  // { type: "衣物销量", clothing: "袜子28", sales: 22 },
  // { type: "衣物销量", clothing: "袜子29", sales: 22 },
  // { type: "衣物销量", clothing: "袜子30", sales: 22 },
  // { type: "衣物销量", clothing: "袜子31", sales: 22 },
  // { type: "衣物销量", clothing: "袜子32", sales: 22 },
  // { type: "衣物销量", clothing: "袜子33", sales: 22 },
  // { type: "衣物销量", clothing: "袜子34", sales: 22 },
  // { type: "衣物销量", clothing: "袜子35", sales: 22 },
  // { type: "衣物销量", clothing: "袜子36", sales: 22 },
  // { type: "衣物销量", clothing: "袜子37", sales: 22 },
  // { type: "衣物销量", clothing: "袜子38", sales: 22 },
  // { type: "衣物销量", clothing: "袜子39", sales: 22 },
  // { type: "衣物销量", clothing: "袜子40", sales: 22 },
  // { type: "衣物销量", clothing: "袜子41", sales: 22 },
  // { type: "衣物销量", clothing: "袜子42", sales: 22 },
  // { type: "衣物销量", clothing: "袜子43", sales: 22 },
  // { type: "衣物销量", clothing: "袜子44", sales: 22 },
  // { type: "衣物销量", clothing: "袜子45", sales: 22 },
  // { type: "衣物销量", clothing: "袜子46", sales: 22 },
  // { type: "衣物销量", clothing: "袜子47", sales: 22 },
  // { type: "衣物销量", clothing: "袜子48", sales: 22 },
  // { type: "衣物销量", clothing: "袜子49", sales: 22 },
  // { type: "衣物销量", clothing: "袜子50", sales: 22 },
  // { type: "衣物销量", clothing: "袜子51", sales: 22 },
  // { type: "衣物销量", clothing: "袜子52", sales: 22 },
  // { type: "衣物销量", clothing: "袜子53", sales: 22 },
  // { type: "衣物销量", clothing: "袜子54", sales: 22 },
  // { type: "衣物销量", clothing: "袜子55", sales: 22 },
  // { type: "衣物销量", clothing: "袜子56", sales: 22 },
  // { type: "衣物销量", clothing: "袜子57", sales: 22 },
  // { type: "衣物销量", clothing: "袜子58", sales: 22 },
  // { type: "衣物销量", clothing: "袜子59", sales: 22 },
  // { type: "衣物销量", clothing: "袜子60", sales: 22 },
  // { type: "衣物销量", clothing: "袜子61", sales: 22 },
  // { type: "衣物销量", clothing: "袜子62", sales: 22 },
  // { type: "衣物销量", clothing: "袜子63", sales: 22 },
  // { type: "衣物销量", clothing: "袜子64", sales: 22 },
  // { type: "衣物销量", clothing: "袜子65", sales: 22 },
  // { type: "衣物销量", clothing: "袜子66", sales: 22 },
  // { type: "衣物销量", clothing: "袜子67", sales: 22 },
  // { type: "衣物销量", clothing: "袜子68", sales: 22 },
  // { type: "衣物销量", clothing: "袜子69", sales: 22 },
  // { type: "衣物销量", clothing: "袜子70", sales: 22 },
  // { type: "衣物销量", clothing: "袜子71", sales: 22 },
  // { type: "衣物销量", clothing: "袜子72", sales: 22 },
  // { type: "衣物销量", clothing: "袜子73", sales: 22 },
  // { type: "衣物销量", clothing: "袜子74", sales: 22 },
  // { type: "衣物销量", clothing: "袜子75", sales: 22 },
  // { type: "衣物销量", clothing: "袜子76", sales: 22 },
  // { type: "衣物销量", clothing: "袜子77", sales: 22 },
  // { type: "衣物销量", clothing: "袜子78", sales: 22 },
  // { type: "衣物销量", clothing: "袜子79", sales: 22 },
  // { type: "衣物销量", clothing: "袜子80", sales: 22 },
  // { type: "衣物销量", clothing: "袜子81", sales: 22 },
  // { type: "衣物销量", clothing: "袜子82", sales: 22 },
  // { type: "衣物销量", clothing: "袜子83", sales: 22 },
  // { type: "衣物销量", clothing: "袜子84", sales: 22 },
  // { type: "衣物销量", clothing: "袜子85", sales: 22 },
  // { type: "衣物销量", clothing: "袜子86", sales: 22 },
  // { type: "衣物销量", clothing: "袜子87", sales: 22 },
  // { type: "衣物销量", clothing: "袜子88", sales: 22 },
  // { type: "衣物销量", clothing: "袜子89", sales: 22 },
  // { type: "衣物销量", clothing: "袜子90", sales: 22 },
  // { type: "衣物销量", clothing: "袜子91", sales: 22 },
  // { type: "衣物销量", clothing: "袜子92", sales: 22 },
  // { type: "衣物销量", clothing: "袜子93", sales: 22 },
  // { type: "衣物销量", clothing: "袜子94", sales: 22 },
  // { type: "衣物销量", clothing: "袜子95", sales: 22 },
  // { type: "衣物销量", clothing: "袜子96", sales: 22 },
  // { type: "衣物销量", clothing: "袜子97", sales: 22 },
  // { type: "衣物销量", clothing: "袜子98", sales: 22 },
  // { type: "衣物销量", clothing: "袜子99", sales: 22 },
  // { type: "衣物销量", clothing: "袜子100", sales: 27 },
];
